//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefonos
    {
        public Telefonos(int idContacto, string numero, string descripcion, Contactos contactos)
        {
            IdContacto = idContacto;
            Numero = numero;
            Descripcion = descripcion;
            Contactos = contactos;
        }

        public int IdContacto { get; set; }
        public string Numero { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Contactos Contactos { get; set; }
    }
}
